### ISSUE TITLE
Values > 8B

### ISSUE THREAD

**Issue by BLepers** [sfu-dis/bztree#14]
Thanks for your implementation of BzTree.

I have noticed that the PiBench wrapper only supports values of up to 8B. Is there a simple way to test the performance of BzTrees with values larger than 8B? (I don't really care if the actual values are persisted, I just want to get a rough idea of the influence of the payload's size on performance.)

Thanks,

**Comment by wangtzh** [comment]
The original BzTree paper mentioned briefly >8B value support, but we didn't have details and the paper focused on 8B pointers, so our current implementation of BzTree only supports 8B values. Any value greater than 8B needs to be represented by a pointer. So you could store pointers to >8B values there for testing, but note that this is more about testing the performance of the allocator being used (e.g., the PMDK allocator which we use) instead of the tree itself. 

I think a "real" inline variable-length value support is what you are after here as it would impact node space use etc; a pointer-based variable-length value implementation wouldn't be able to show. On a high level my guess is it would cause more splits which can significantly lower performance given the internal nodes of BzTree are copy-on-insert, plus high overhead again from the allocator.

Hope that helps!
